sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade setuptools
  - pip install html5lib==0.9999999
  - pip install --upgrade pip --cache-dir $HOME/.cache/pip
  - pip install coveralls --cache-dir $HOME/.cache/pip
  - pip install flake8 --cache-dir $HOME/.cache/pip
  - pip install -r requirements-dev.txt --cache-dir $HOME/.cache/pip
  - pip install -e . --cache-dir $HOME/.cache/pip
script:
  - flake8 nurseconnect
  - py.test
notifications:
  slack: praekelt:37JlRu8DWDq9ZdTowf5cgMoN
services:
  - elasticsearch
before_script:
  - sleep 10
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
    secure: "insert encrypted pypi password here"
  on:
    tags: true
    all_branches: true
